# Generated by Django 5.2.7 on 2025-10-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='expertise',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
