# Generated by Django 5.2.7 on 2025-10-23 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructorApp', '0005_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='course',
            new_name='course_instance',
        ),
    ]
