# Generated by Django 5.2.7 on 2025-10-28 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructorApp', '0008_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
